#### 피쳐 전처리
- 수치형 피쳐 전처리 -> 스케일링 범위
- 범주형 피쳐 전처리 -> 인코딩

In [18]:
# 모듈 로딩
from sklearn.preprocessing import LabelEncoder


In [19]:
# 정수 인코딩
items = ['TV', '냉장고', '선풍기', '에어컨']

In [20]:
# 라벨/정수 인코더 인스턴스 생성
encoder = LabelEncoder()

# 라벨/정수 인코더의 범위 및 맵핑 작업
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 2 3]


In [21]:
# 원핫 인코딩
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [22]:
# 2D로 변경
items = np.array(items).reshape(-1,1)
print(items)

one_encoder = OneHotEncoder()
one_encoder.fit(items)
onelabels = one_encoder.transform(items)

print('원 핫 인코딩 데이터')
print(onelabels.toarray())
print('원 핫 인코딩 데이터 차원')
print(onelabels.shape)

[['TV']
 ['냉장고']
 ['선풍기']
 ['에어컨']]
원 핫 인코딩 데이터
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
원 핫 인코딩 데이터 차원
(4, 4)


In [23]:
# 정수 인코딩 -> 범주형 피쳐
from sklearn.preprocessing import OrdinalEncoder

In [24]:
data = [['male', 'C', 'child'],['fmale', 'T', 'man']]

In [25]:
# 정수 인코더 instance 생성
odEncoding = OrdinalEncoder()
odEncoding.fit(data)
label = odEncoding.transform(data)
print('인코딩 변환값:', label)

인코딩 변환값: [[1. 0. 0.]
 [0. 1. 1.]]
